version: 0.0
os: linux

files:             
  - source: ./demo-0.0.1-SNAPSHOT.war
    destination: /opt/tomcat/webapps   

hooks:
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
  ApplicationStart:
   - location: ./applicationStart.sh
     timeout: 500
     runas: centos
  ApplicationStop:
   - location: ./applicationStop.sh
     timeout: 180
     runas: centos
