version: 0.0
os: linux

files:             
  - source: ./demo-0.0.1-SNAPSHOT.war
    destination: /usr/share/tomcat/webapps   

hooks:
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
  ApplicationStart:
   - location: ./applicationStart.sh
     timeout: 400
     runas: centos
# ValidateService:
#  - location: ./validateService.sh
#    timeout: 180
#    runas: centos
