version: 0.0
os: linux

files:             
  - source: ./demo-0.0.1-SNAPSHOT.war
    destination: /opt/tomcat/apache-tomcat-9.0.27/webapps   

hooks:
  ApplicationStop:
   - location: ./applicationStop.sh
     timeout: 180
     runas: centos
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
  ApplicationStart:
   - location: ./applicationStart.sh
     timeout: 500
     runas: centos
# ValidateService:
#  - location: ./validateService.sh
#    timeout: 180
#    runas: centos
